env: "dev"
name: "web-tpl"
http:
  listen: ":8080"

# gin的中间件日志
web_server_log:
  enable: true
  log_id_show_header: true
  log_path: "logs/access.log"
  log_format: "text" #text json
  output: "file" #file stdout
  ship_path:
    - "/favicon.ico"

log:
  level: "info"
  output: "stdout" #file stdout
  name: "log/app.log"
  log_format: "text" #text json


#app:DBR("A"):
db:
  default:
    logs:
      enable: true
      level: "info"
      format: "text" #json or text
      type: "file"  #stdout or file
      path: "logs/sql-default.log"
    write:
      host: "127.0.0.1"
      port: "3306"
      database: "go_tpl"
      username: "root"
      password: "20212021"
      charset: "utf8mb4"
      timeout: 5000
      write_time_out: 5000
      read_time_out: 5000
      max_idle_conns: 5      #最大空闲数
      max_open_conns: 1000   #最大连接数
    read:
      host: "127.0.0.1"
      port: "3306"
      database: "go_tpl"
      username: "root"
      password: "20212021"
      charset: "utf8mb4"
      timeout: 5000
      write_time_out: 5000
      read_time_out: 5000
      max_idle_conns: 5      #最大空闲数
      max_open_conns: 1000   #最大连接数


redis:
  default:
    write:
      host: "127.0.0.1:6479"
      password: "20212021"
      pool_size: 10
      idle_timeout: '5000ms' //ms 闲置时间
      read_timeout: '3000ms'
      write_timeout: '3000ms'
      min_idle_conns: 5
      retries: 3 //重试
      db: 0
    read:
      host: "127.0.0.1:6479"
      password: "20212021"
      pool_size: 10
      idle_timeout: '5000ms' //ms
      read_timeout: '3000ms'
      write_timeout: '3000ms'
      min_idle_conns: 5
      retries: 3
      db: 0